### ISSUE TITLE
Help people get photos

### ISSUE THREAD

**Issue by marijnh** [OpenTechSchool/js-beginners-2#1]
I think that some students don't even know what pixels are at this point. And there's no guarantee that there'll be image-editing software installed on their machine. This might turn out to be a time waster.

Maybe we should provide a bunch of pictures to choose from? Or at least find and link to an online service that helps resize pictures. (Does anyone know one that's halfway user-friendly?)

**Comment by theophani** [comment]
I mentioned Flickr because Flickr makes it easy to get the exact sizes needed. I could add more detail there, as well as "have no idea what pictures to use? use these:" with links.

**Comment by marijnh** [comment]
Ah, I didn't know flickr allows you to download per size. More details and suggestions still sounds good.

**Comment by theophani** [comment]
resolved by:
https://github.com/OpenTechSchool/js-beginners-day2/commit/f75da68f2426748a13ba7f272e7267c5293b79f4

**Comment by marijnh** [comment]
Marvellous.
