### ISSUE TITLE
German versions

### ISSUE THREAD

**Issue by knuton** [OpenTechSchool/js-beginners-2#10]
Is anyone working on translations of pages 1 through 4 to German? If so, please leave a note here stating which page you are working on to prevent several people translating the same parts.

I will tackle whatever is left during or after the opening meeting today.

**Comment by molily** [comment]
I’m working on the PAGE ONE (in numbers: 1) at the moment ;)

**Comment by molily** [comment]
PR for page 1 ready.
I’ll go on with page 2 now.

**Comment by knuton** [comment]
Starting page 3.

**Comment by molily** [comment]
I’m still on page 2, will finish tomorrow

**Comment by knuton** [comment]
Page 3 done, #14.
