### ISSUE TITLE
Use curly braces for single-line blocks, too

### ISSUE THREAD

**Issue by xMartin** [OpenTechSchool/js-beginners-2#20]
It would just be a little less confusing if the example code didn't show people the option of leaving curly braces out for single-line ifs and fors and the like.

**Comment by sdepold** [comment]
Word.

Am 22.07.2012 um 13:05 schrieb xMartin
reply@reply.github.com:

**Comment by janl** [comment]
Major +1

**Comment by gryzzly** [comment]
+1

**Comment by gnunicorn** [comment]
Yep. +1
