### ISSUE TITLE
for-loop more or less unknown

### ISSUE THREAD

**Issue by sdepold** [OpenTechSchool/js-beginners-2#24]
many people i talked to, had probs with the syntax and the functionality of the for loop (page4). we should explain that loop more detailed or replace it with a while loop

**Comment by molily** [comment]
Agree, had the same experience. The for loop is hard to understand because there’s so much on one line. I had to break it up into multiple lines for explanation. Also there’s <code>i++</code> which isn’t used or explained elsewhere (except in the space invaders script).

**Comment by sjockers** [comment]
This has actually been fixed during the preparation of the workshop at campus party. -> closed.

**Comment by sdepold** [comment]
Great :)

Am 21.09.2012 um 16:19 schrieb sjockers notifications@github.com:

This has actually been fixed during the preparation of the workshop at
campus party. -> closed.

—
Reply to this email directly or view it on
GitHubhttps://github.com/OpenTechSchool/js-beginners-day2/issues/24#issuecomment-8766046.
