### ISSUE TITLE
Mark as outdated and not as part 2 of "the" workshop

### ISSUE THREAD

**Issue by xMartin** [OpenTechSchool/js-beginners-2#31]
This used to be "day 2" of the full-weekend workshop "JavaScript for absolute beginners". This part introduces the DOM as the first part only uses canvas to learn basic programming in JavaScript.

While part 1 is rather timeless and still works well for us, this part is quite outdated, as it contains animations in JavaScript that you'd do with CSS these days.

In order to not confuse people and also be more explicit what it's about, let's remove the notion of "day/part 2" of something and rather give it a descriptive name like "JS and the DOM" or "JS for web pages". I'd also suggest to mark it is outdated.

See also https://github.com/OpenTechSchool/js-beginners-1/issues/31

**Comment by xMartin** [comment]
What do you think @bastianalbers @gsambrotta @tobmaster @theophani

**Comment by bastianalbers** [comment]
Yes, i agree. While this was good back then i'd like to give this a refresh as well. Happy to brainstorm on this and give some input. I would be pretty happy to have this in an updated version as it introduces some of the basic building blocks everyone should know about.
