### ISSUE TITLE
Intro line needs German translation

### ISSUE THREAD

**Issue by theophani** [OpenTechSchool/js-beginners-2#8]
Anyone care to try to translate Tiffany-English into German?

"The internet is powered with magic, or as we like to call it, JavaScript."

**Comment by knuton** [comment]
Das Internet ist eine Wundermaschine, getrieben von Magie, oder – wie wir es nennen – JavaScript.

**Comment by theophani** [comment]
Awesome. Now we just need t-shirts that say "Das Internet ist eine Wundermaschine".

resolved by:
https://github.com/OpenTechSchool/js-beginners-day2/commit/b600655e209d0816d0c331b697ca4b48450a2a0d
